- name: generate-snake-game-from-github-contribution-grid
  id: generate-snake
  uses: ./
  with:
    github_user_name: palmiery
    outputs: |
      dist/github-contribution-grid-snake.svg
      dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

- name: ensure the generated file exists
  run: |
    ls dist
    test -f dist/github-contribution-grid-snake.svg
    test -f dist/github-contribution-grid-snake-dark.svg
    test -f dist/github-contribution-grid-snake.gif

- uses: crazy-max/ghaction-github-pages@v4.1.0
  with:
    target_branch: output
    build_dir: dist
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

test-action-svg-only:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1

    - run: bun install --frozen-lockfile

    - name: build svg-only action
      run: |
        npm run build:action
        rm -r svg-only/dist
        mv packages/action/dist svg-only/dist

    - name: generate-snake-game-from-github-contribution-grid
      id: generate-snake
      uses: ./svg-only
      with:
        github_user_name: palmiery
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          dist/github-contribution-grid-snake-blue.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    - name: ensure the generated file exists
      run: |
        ls dist
        test -f dist/github-contribution-grid-snake.svg
        test -f dist/github-contribution-grid-snake-dark.svg
        test -f dist/github-contribution-grid-snake-blue.svg
